// Single typed source of truth for the PROTO-001 BFF wire contract,
// mirroring docs/openapi/openapi.yaml exactly. Per GA-015 (Codex Spec
// line 128: "Frontend 不得直接呼叫 domain module；只能經 BFF API 與
// docs/openapi contract 生成 client"), apps/web/apps/admin must consume
// the BFF only through this module — never a hand-rolled, independently
// shaped fetch() call. That duplication is exactly what let PROTO-001A's
// original camelCase CampaignSummary interface in apps/web silently drift
// out of sync with the real (snake_case) API response for several
// commits, undetected until a real browser reload surfaced it.
//
// This client is hand-authored rather than machine-generated by an
// approved OpenAPI codegen tool, because no such tool is an approved
// dependency in this repository (CLAUDE.md's Toolchain Boundary forbids
// introducing an unapproved package/framework without ADR-000 approval).
// It still satisfies GA-015's actual intent — one typed contract module,
// no duplicate shadow DTOs — for exactly PROTO-001's own routes (FND-013's
// documented minimum-subset scope), not a full generated client for every
// future epic.
//
// Limited to the routes apps/web's PROTO-001 demo journey actually calls:
// campaign current, QR scan, reward draw (also used for idempotent
// replay — same request/response shape), member center, admin trace.

export interface CanonicalErrorEnvelope {
  error_code: string;
  message: string;
  details: Record<string, unknown> | null;
  correlation_id: string;
  retry_after_seconds: number | null;
}

export interface CampaignSummary {
  campaign_id: string;
  market_id: string;
  name: string;
  status: string;
}

export interface QrScanRequest {
  code: string;
  client_request_id: string;
}

export interface QrScanResult {
  qr_code_id: string;
  state: "USED";
}

export interface DrawRequest {
  campaign_id: string;
  client_request_id: string;
}

export interface DrawResult {
  draw_id: string;
  state: "DrawReserved";
  draw_result: {
    result_type: "PRIZE" | "POINT" | "NO_WIN";
    prize_tier: string | null;
    point_amount: number | null;
  };
}

export interface WalletSummary {
  available_points: number;
}

export interface MemberCenterSummary {
  member_id: string;
  display_name: string;
  wallet_summary: WalletSummary;
  collection: Array<{ item_id: string; unlocked: boolean }>;
}

export interface AuditLogEntry {
  event_id: string;
  event_type: string;
  aggregate_type: string;
  aggregate_id: string;
  status: string;
  correlation_id: string;
  causation_id: string | null;
  created_at: string;
  published_at: string | null;
}

export type ApiResult<T> =
  | { ok: true; status: number; body: T }
  | { ok: false; status: number; body: CanonicalErrorEnvelope | null };

export interface ApiClientOptions {
  correlationId?: string;
}

async function call<T>(baseUrl: string, path: string, init: RequestInit): Promise<ApiResult<T>> {
  const response = await fetch(`${baseUrl}${path}`, init);
  const body = await response.json().catch(() => null);
  if (response.ok) {
    return { ok: true, status: response.status, body: body as T };
  }
  return { ok: false, status: response.status, body: body as CanonicalErrorEnvelope | null };
}

function withCorrelationHeader(options: ApiClientOptions | undefined, extra: Record<string, string> = {}) {
  return {
    ...extra,
    ...(options?.correlationId ? { "x-correlation-id": options.correlationId } : {}),
  };
}

export function createApiClient(baseUrl: string) {
  return {
    async getCurrentCampaign(options?: ApiClientOptions): Promise<ApiResult<CampaignSummary>> {
      return call(baseUrl, "/api/v1/campaigns/current", {
        headers: withCorrelationHeader(options),
        cache: "no-store",
      });
    },

    async scanQr(request: QrScanRequest, options?: ApiClientOptions): Promise<ApiResult<QrScanResult>> {
      return call(baseUrl, "/api/v1/qr/scan", {
        method: "POST",
        headers: withCorrelationHeader(options, { "Content-Type": "application/json" }),
        body: JSON.stringify(request),
      });
    },

    async createDraw(
      request: DrawRequest,
      idempotencyKey: string,
      options?: ApiClientOptions,
    ): Promise<ApiResult<DrawResult>> {
      return call(baseUrl, "/api/v1/reward/draws", {
        method: "POST",
        headers: withCorrelationHeader(options, {
          "Content-Type": "application/json",
          "Idempotency-Key": idempotencyKey,
        }),
        body: JSON.stringify(request),
      });
    },

    async getMemberCenter(options?: ApiClientOptions): Promise<ApiResult<MemberCenterSummary>> {
      return call(baseUrl, "/api/v1/me", { headers: withCorrelationHeader(options), cache: "no-store" });
    },

    async getAdminAuditLog(correlationId: string): Promise<ApiResult<AuditLogEntry[]>> {
      return call(baseUrl, `/admin/api/v1/audit-log?correlation_id=${encodeURIComponent(correlationId)}`, {});
    },
  };
}

export type ApiClient = ReturnType<typeof createApiClient>;
