-- owning_context: ip_asset
-- description: Create ip_asset.collection_item (deterministic catalog) and ip_asset.member_unlock (per-member unlock state) for PROTO-001F. No standalone GET /api/v1/collection route exists; collection data is composed into GET /api/v1/me only, per the binding read-composition rule. Unlocking is idempotent per (member_id, item_id).
-- rollback_notes: Down drops member_unlock then collection_item, each guarded by an explicit emptiness check; once any row exists in either table, destructive rollback is prohibited and correction is forward-fix only.
-- forward_fix_notes: After downstream adoption (any row written), correct these tables' structure through a new forward migration. Never edit or destructively reverse this migration in a shared environment.
--
-- This file is a non-executable template. It contains no real DDL and must
-- not be edited to add one. Copy its structure into a new, properly named
-- migration file (see migrations/README.md) instead.
--
-- Real application, domain, or platform schema changes are out of scope for
-- FND-003 and belong to FND-004 (schema isolation) and later tasks.
--
-- node-pg-migrate's --single-transaction default (see migrations/README.md)
-- wraps every pending migration applied in a single run inside one
-- BEGIN/COMMIT/ROLLBACK. If a specific statement cannot run inside a
-- transaction (for example certain PostgreSQL DDL forms), document that
-- constraint explicitly in this file's description field before authoring
-- real SQL.
--
-- Once a migration has been applied to any shared (non-local, non-ephemeral)
-- environment, do not edit this file's history. Author a new forward-fix
-- migration instead, and record the correction in that new file's
-- forward_fix_notes field.

-- Up Migration

CREATE TABLE ip_asset.collection_item (
  item_id TEXT PRIMARY KEY,
  campaign_id TEXT NOT NULL,
  name TEXT NOT NULL,
  linked_prize_tier_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE ip_asset.member_unlock (
  unlock_id UUID PRIMARY KEY,
  member_id TEXT NOT NULL,
  item_id TEXT NOT NULL REFERENCES ip_asset.collection_item (item_id),
  source_type TEXT NOT NULL,
  source_id TEXT NOT NULL,
  correlation_id TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT member_unlock_member_item_unique UNIQUE (member_id, item_id)
);

CREATE INDEX member_unlock_member_id_idx ON ip_asset.member_unlock (member_id);

GRANT SELECT ON ip_asset.collection_item TO app_rw_user;
GRANT SELECT, INSERT ON ip_asset.member_unlock TO app_rw_user;

-- Down Migration

-- DROP TABLE ... RESTRICT alone only refuses when another object depends on
-- this table — it does not check row content. These explicit guards are what
-- actually enforce the rollback_notes' "only while empty" rule.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM ip_asset.member_unlock LIMIT 1) THEN
    RAISE EXCEPTION 'ip_asset.member_unlock is not empty; destructive rollback is prohibited once any row exists. Forward-fix only.';
  END IF;
END $$;

DROP TABLE ip_asset.member_unlock RESTRICT;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM ip_asset.collection_item LIMIT 1) THEN
    RAISE EXCEPTION 'ip_asset.collection_item is not empty; destructive rollback is prohibited once any row exists. Forward-fix only.';
  END IF;
END $$;

DROP TABLE ip_asset.collection_item RESTRICT;
