-- owning_context: platform
-- description: Create the twelve approved bounded-context schemas, harden schema CREATE privileges, and grant schema-level USAGE to app_rw_user without granting any object-level privilege.
-- rollback_notes: Down may drop the twelve schemas only while every schema remains empty. DROP SCHEMA uses RESTRICT and never CASCADE. Public-schema hardening is not reversed by down. Once any downstream object exists, destructive rollback is prohibited and correction is forward-fix only.
-- forward_fix_notes: After downstream adoption, correct schema ownership or privileges through a new forward migration. Never edit or destructively reverse this migration in a shared environment.
--
-- This file is a non-executable template. It contains no real DDL and must
-- not be edited to add one. Copy its structure into a new, properly named
-- migration file (see migrations/README.md) instead.
--
-- Real application, domain, or platform schema changes are out of scope for
-- FND-003 and belong to FND-004 (schema isolation) and later tasks.
--
-- node-pg-migrate's --single-transaction default (see migrations/README.md)
-- wraps every pending migration applied in a single run inside one
-- BEGIN/COMMIT/ROLLBACK. If a specific statement cannot run inside a
-- transaction (for example certain PostgreSQL DDL forms), document that
-- constraint explicitly in this file's description field before authoring
-- real SQL.
--
-- Once a migration has been applied to any shared (non-local, non-ephemeral)
-- environment, do not edit this file's history. Author a new forward-fix
-- migration instead, and record the correction in that new file's
-- forward_fix_notes field.

-- Up Migration

CREATE SCHEMA platform;
CREATE SCHEMA campaign;
CREATE SCHEMA wallet;
CREATE SCHEMA qr;
CREATE SCHEMA reward;
CREATE SCHEMA notification;
CREATE SCHEMA compliance;
CREATE SCHEMA crm;
CREATE SCHEMA team;
CREATE SCHEMA ip_asset;
CREATE SCHEMA analytics;
CREATE SCHEMA commerce;

REVOKE CREATE ON SCHEMA public FROM PUBLIC;

REVOKE CREATE ON SCHEMA
  platform,
  campaign,
  wallet,
  qr,
  reward,
  notification,
  compliance,
  crm,
  team,
  ip_asset,
  analytics,
  commerce
FROM PUBLIC;

-- app_rw_user is a deployment precondition; this migration does not create
-- it. If it is absent, the following statement fails naturally with
-- SQLSTATE 42704 (role "app_rw_user" does not exist), and the migration
-- runner's single transaction rolls back every preceding statement above.
REVOKE CREATE ON SCHEMA
  platform,
  campaign,
  wallet,
  qr,
  reward,
  notification,
  compliance,
  crm,
  team,
  ip_asset,
  analytics,
  commerce
FROM app_rw_user;

GRANT USAGE ON SCHEMA
  platform,
  campaign,
  wallet,
  qr,
  reward,
  notification,
  compliance,
  crm,
  team,
  ip_asset,
  analytics,
  commerce
TO app_rw_user;

-- Down Migration

DROP SCHEMA
  platform,
  campaign,
  wallet,
  qr,
  reward,
  notification,
  compliance,
  crm,
  team,
  ip_asset,
  analytics,
  commerce
RESTRICT;
