-- owning_context: campaign
-- description: Create campaign.campaign as the source-of-truth table for PROTO-001's single TW demo campaign (PROTO-001A minimum shape).
-- rollback_notes: Down drops campaign.campaign only while the table is empty, using DROP TABLE RESTRICT, guarded by an explicit emptiness check. Once any row exists, destructive rollback is prohibited and correction is forward-fix only.
-- forward_fix_notes: After downstream adoption (any row written), correct this table's structure through a new forward migration. Never edit or destructively reverse this migration in a shared environment.
--
-- This file is a non-executable template. It contains no real DDL and must
-- not be edited to add one. Copy its structure into a new, properly named
-- migration file (see migrations/README.md) instead.
--
-- Real application, domain, or platform schema changes are out of scope for
-- FND-003 and belong to FND-004 (schema isolation) and later tasks.
--
-- node-pg-migrate's --single-transaction default (see migrations/README.md)
-- wraps every pending migration applied in a single run inside one
-- BEGIN/COMMIT/ROLLBACK. If a specific statement cannot run inside a
-- transaction (for example certain PostgreSQL DDL forms), document that
-- constraint explicitly in this file's description field before authoring
-- real SQL.
--
-- Once a migration has been applied to any shared (non-local, non-ephemeral)
-- environment, do not edit this file's history. Author a new forward-fix
-- migration instead, and record the correction in that new file's
-- forward_fix_notes field.

-- Up Migration

CREATE TABLE campaign.campaign (
  campaign_id TEXT PRIMARY KEY,
  market_id TEXT NOT NULL,
  name TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('Draft', 'Active', 'Ending', 'Archived', 'Hidden')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Read-only for app_rw_user in the Prototype: campaign creation/editing is
-- Admin-authored seed only (docs/codex-task-packages/PROTO-001.md §6), no
-- write endpoint exists.
GRANT SELECT ON campaign.campaign TO app_rw_user;

-- Down Migration

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM campaign.campaign LIMIT 1) THEN
    RAISE EXCEPTION 'campaign.campaign is not empty; destructive rollback is prohibited once any row exists. Forward-fix only.';
  END IF;
END $$;

DROP TABLE campaign.campaign RESTRICT;
