-- owning_context: crm
-- description: Create crm.member as the demo-member identity table for PROTO-001B. No public or internal API route reads or writes this table; the demo member is injected via deterministic seed/session tooling only.
-- rollback_notes: Down drops crm.member only while the table is empty, using DROP TABLE RESTRICT, guarded by an explicit emptiness check. Once any row exists, destructive rollback is prohibited and correction is forward-fix only.
-- forward_fix_notes: After downstream adoption (any row written), correct this table's structure through a new forward migration. Never edit or destructively reverse this migration in a shared environment.
--
-- This file is a non-executable template. It contains no real DDL and must
-- not be edited to add one. Copy its structure into a new, properly named
-- migration file (see migrations/README.md) instead.
--
-- Real application, domain, or platform schema changes are out of scope for
-- FND-003 and belong to FND-004 (schema isolation) and later tasks.
--
-- node-pg-migrate's --single-transaction default (see migrations/README.md)
-- wraps every pending migration applied in a single run inside one
-- BEGIN/COMMIT/ROLLBACK. If a specific statement cannot run inside a
-- transaction (for example certain PostgreSQL DDL forms), document that
-- constraint explicitly in this file's description field before authoring
-- real SQL.
--
-- Once a migration has been applied to any shared (non-local, non-ephemeral)
-- environment, do not edit this file's history. Author a new forward-fix
-- migration instead, and record the correction in that new file's
-- forward_fix_notes field.

-- Up Migration

CREATE TABLE crm.member (
  member_id TEXT PRIMARY KEY,
  display_name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

GRANT SELECT ON crm.member TO app_rw_user;

-- Down Migration

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM crm.member LIMIT 1) THEN
    RAISE EXCEPTION 'crm.member is not empty; destructive rollback is prohibited once any row exists. Forward-fix only.';
  END IF;
END $$;

DROP TABLE crm.member RESTRICT;
