-- owning_context: reward
-- description: Create reward.prize_tier, reward.prize_token, and reward.draw_ledger for PROTO-001D DrawReserved-time result determination. Prize inventory is modeled as individual claimable token rows (per CLAUDE.md's GA rule: draws use DB SKIP LOCKED, not Redis/memory TokenSource), claimed atomically via SELECT ... FOR UPDATE SKIP LOCKED so oversell is structurally impossible. draw_ledger is the immutable, idempotent record of each DrawReserved-time result; a replay never re-randomizes.
-- rollback_notes: Down drops draw_ledger, then prize_token, then prize_tier, each guarded by an explicit emptiness check; once any row exists in any of these tables, destructive rollback is prohibited and correction is forward-fix only.
-- forward_fix_notes: After downstream adoption (any row written), correct these tables' structure through a new forward migration. Never edit or destructively reverse this migration in a shared environment.
--
-- This file is a non-executable template. It contains no real DDL and must
-- not be edited to add one. Copy its structure into a new, properly named
-- migration file (see migrations/README.md) instead.
--
-- Real application, domain, or platform schema changes are out of scope for
-- FND-003 and belong to FND-004 (schema isolation) and later tasks.
--
-- node-pg-migrate's --single-transaction default (see migrations/README.md)
-- wraps every pending migration applied in a single run inside one
-- BEGIN/COMMIT/ROLLBACK. If a specific statement cannot run inside a
-- transaction (for example certain PostgreSQL DDL forms), document that
-- constraint explicitly in this file's description field before authoring
-- real SQL.
--
-- Once a migration has been applied to any shared (non-local, non-ephemeral)
-- environment, do not edit this file's history. Author a new forward-fix
-- migration instead, and record the correction in that new file's
-- forward_fix_notes field.

-- Up Migration

CREATE TABLE reward.prize_tier (
  prize_tier_id TEXT PRIMARY KEY,
  campaign_id TEXT NOT NULL,
  tier_name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE reward.prize_token (
  token_id TEXT PRIMARY KEY,
  campaign_id TEXT NOT NULL,
  prize_tier_id TEXT NOT NULL REFERENCES reward.prize_tier (prize_tier_id),
  status TEXT NOT NULL DEFAULT 'Available' CHECK (status IN ('Available', 'Claimed')),
  claimed_by_draw_id TEXT,
  claimed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX prize_token_campaign_status_idx ON reward.prize_token (campaign_id, status);

CREATE TABLE reward.draw_ledger (
  draw_id TEXT PRIMARY KEY,
  campaign_id TEXT NOT NULL,
  member_id TEXT NOT NULL,
  idempotency_key TEXT NOT NULL UNIQUE,
  client_request_id TEXT NOT NULL,
  request_fingerprint TEXT NOT NULL,
  result_type TEXT NOT NULL CHECK (result_type IN ('PRIZE', 'POINT', 'NO_WIN')),
  prize_tier_id TEXT REFERENCES reward.prize_tier (prize_tier_id),
  point_amount INTEGER,
  correlation_id TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT draw_ledger_point_amount_integer CHECK (point_amount IS NULL OR point_amount >= 0)
);

GRANT SELECT ON reward.prize_tier TO app_rw_user;
GRANT SELECT, UPDATE ON reward.prize_token TO app_rw_user;
GRANT SELECT, INSERT ON reward.draw_ledger TO app_rw_user;

-- Down Migration

-- DROP TABLE ... RESTRICT alone only refuses when another object depends on
-- this table — it does not check row content. These explicit guards are what
-- actually enforce the rollback_notes' "only while empty" rule.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM reward.draw_ledger LIMIT 1) THEN
    RAISE EXCEPTION 'reward.draw_ledger is not empty; destructive rollback is prohibited once any row exists. Forward-fix only.';
  END IF;
END $$;

DROP TABLE reward.draw_ledger RESTRICT;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM reward.prize_token LIMIT 1) THEN
    RAISE EXCEPTION 'reward.prize_token is not empty; destructive rollback is prohibited once any row exists. Forward-fix only.';
  END IF;
END $$;

DROP TABLE reward.prize_token RESTRICT;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM reward.prize_tier LIMIT 1) THEN
    RAISE EXCEPTION 'reward.prize_tier is not empty; destructive rollback is prohibited once any row exists. Forward-fix only.';
  END IF;
END $$;

DROP TABLE reward.prize_tier RESTRICT;
