-- owning_context: platform
-- description: Create platform.event_outbox as the transactional-outbox source of truth for domain/integration events (FND-005 minimum subset). No delivery/relay mechanism is implemented; this migration creates only the table and its indexes.
-- rollback_notes: Down drops platform.event_outbox only while the table is empty, using DROP TABLE (no CASCADE). Once any row exists, destructive rollback is prohibited and correction is forward-fix only.
-- forward_fix_notes: After downstream adoption (any row written), correct this table's structure through a new forward migration. Never edit or destructively reverse this migration in a shared environment.
--
-- This file is a non-executable template. It contains no real DDL and must
-- not be edited to add one. Copy its structure into a new, properly named
-- migration file (see migrations/README.md) instead.
--
-- Real application, domain, or platform schema changes are out of scope for
-- FND-003 and belong to FND-004 (schema isolation) and later tasks.
--
-- node-pg-migrate's --single-transaction default (see migrations/README.md)
-- wraps every pending migration applied in a single run inside one
-- BEGIN/COMMIT/ROLLBACK. If a specific statement cannot run inside a
-- transaction (for example certain PostgreSQL DDL forms), document that
-- constraint explicitly in this file's description field before authoring
-- real SQL.
--
-- Once a migration has been applied to any shared (non-local, non-ephemeral)
-- environment, do not edit this file's history. Author a new forward-fix
-- migration instead, and record the correction in that new file's
-- forward_fix_notes field.

-- Up Migration

CREATE TABLE platform.event_outbox (
  event_id UUID PRIMARY KEY,
  event_type TEXT NOT NULL,
  aggregate_type TEXT NOT NULL,
  aggregate_id TEXT NOT NULL,
  aggregate_version INTEGER NOT NULL,
  payload_json JSONB NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'PUBLISHED', 'FAILED', 'DEAD')),
  retry_count INTEGER NOT NULL DEFAULT 0,
  next_retry_at TIMESTAMPTZ,
  correlation_id TEXT NOT NULL,
  causation_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  published_at TIMESTAMPTZ
);

CREATE INDEX event_outbox_status_idx ON platform.event_outbox (status);
CREATE INDEX event_outbox_correlation_id_idx ON platform.event_outbox (correlation_id);

GRANT SELECT, INSERT ON platform.event_outbox TO app_rw_user;

-- Down Migration

-- DROP TABLE ... RESTRICT alone only refuses when another object depends on
-- this table (e.g. a foreign key) — it does not check row content. This
-- explicit guard is what actually enforces the rollback_notes' "only while
-- the table is empty" rule; without it, DROP TABLE would silently destroy
-- real event data.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM platform.event_outbox LIMIT 1) THEN
    RAISE EXCEPTION 'platform.event_outbox is not empty; destructive rollback is prohibited once any row exists. Forward-fix only.';
  END IF;
END $$;

DROP TABLE platform.event_outbox RESTRICT;
