-- owning_context: qr
-- description: Create qr.code and qr.scan_event for PROTO-001C atomic one-time-use QR scan enforcement and scan idempotency (client_request_id + request_fingerprint replay). qr.code stores only a code_hash — the raw signed QR value is never persisted. No public route exists for these tables besides POST /api/v1/qr/scan.
-- rollback_notes: Down drops qr.scan_event then qr.code, each guarded by an explicit emptiness check; once any row exists in either table, destructive rollback is prohibited and correction is forward-fix only.
-- forward_fix_notes: After downstream adoption (any row written), correct these tables' structure through a new forward migration. Never edit or destructively reverse this migration in a shared environment.
--
-- This file is a non-executable template. It contains no real DDL and must
-- not be edited to add one. Copy its structure into a new, properly named
-- migration file (see migrations/README.md) instead.
--
-- Real application, domain, or platform schema changes are out of scope for
-- FND-003 and belong to FND-004 (schema isolation) and later tasks.
--
-- node-pg-migrate's --single-transaction default (see migrations/README.md)
-- wraps every pending migration applied in a single run inside one
-- BEGIN/COMMIT/ROLLBACK. If a specific statement cannot run inside a
-- transaction (for example certain PostgreSQL DDL forms), document that
-- constraint explicitly in this file's description field before authoring
-- real SQL.
--
-- Once a migration has been applied to any shared (non-local, non-ephemeral)
-- environment, do not edit this file's history. Author a new forward-fix
-- migration instead, and record the correction in that new file's
-- forward_fix_notes field.

-- Up Migration

CREATE TABLE qr.code (
  qr_code_id TEXT PRIMARY KEY,
  code_hash TEXT NOT NULL UNIQUE,
  campaign_id TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'Unused' CHECK (status IN ('Unused', 'Used', 'Inactive')),
  used_by_member_id TEXT,
  used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE qr.scan_event (
  scan_event_id UUID PRIMARY KEY,
  qr_code_id TEXT NOT NULL REFERENCES qr.code (qr_code_id),
  member_id TEXT NOT NULL,
  client_request_id TEXT NOT NULL UNIQUE,
  request_fingerprint TEXT NOT NULL,
  correlation_id TEXT NOT NULL,
  outcome_json JSONB NOT NULL,
  result_code TEXT NOT NULL CHECK (result_code IN ('SUCCESS', 'ALREADY_USED', 'INACTIVE')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX scan_event_qr_code_id_idx ON qr.scan_event (qr_code_id);

GRANT SELECT, UPDATE ON qr.code TO app_rw_user;
GRANT SELECT, INSERT ON qr.scan_event TO app_rw_user;

-- Down Migration

-- DROP TABLE ... RESTRICT alone only refuses when another object depends on
-- this table — it does not check row content. These explicit guards are what
-- actually enforce the rollback_notes' "only while empty" rule.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM qr.scan_event LIMIT 1) THEN
    RAISE EXCEPTION 'qr.scan_event is not empty; destructive rollback is prohibited once any row exists. Forward-fix only.';
  END IF;
END $$;

DROP TABLE qr.scan_event RESTRICT;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM qr.code LIMIT 1) THEN
    RAISE EXCEPTION 'qr.code is not empty; destructive rollback is prohibited once any row exists. Forward-fix only.';
  END IF;
END $$;

DROP TABLE qr.code RESTRICT;
