-- owning_context: wallet
-- description: Create wallet.ledger_entry as the append-only points ledger for PROTO-001E. Only INSERT is granted to app_rw_user (no UPDATE, no DELETE) — append-only is enforced at the database permission level, not just application discipline. UNIQUE(source_type, source_id) makes posting idempotent per source (e.g. one entry per DrawReserved POINT outcome).
-- rollback_notes: Down drops wallet.ledger_entry only while empty, guarded by an explicit emptiness check; once any row exists, destructive rollback is prohibited and correction is forward-fix only.
-- forward_fix_notes: After downstream adoption (any row written), correct this table's structure through a new forward migration. Never edit or destructively reverse this migration in a shared environment.
--
-- This file is a non-executable template. It contains no real DDL and must
-- not be edited to add one. Copy its structure into a new, properly named
-- migration file (see migrations/README.md) instead.
--
-- Real application, domain, or platform schema changes are out of scope for
-- FND-003 and belong to FND-004 (schema isolation) and later tasks.
--
-- node-pg-migrate's --single-transaction default (see migrations/README.md)
-- wraps every pending migration applied in a single run inside one
-- BEGIN/COMMIT/ROLLBACK. If a specific statement cannot run inside a
-- transaction (for example certain PostgreSQL DDL forms), document that
-- constraint explicitly in this file's description field before authoring
-- real SQL.
--
-- Once a migration has been applied to any shared (non-local, non-ephemeral)
-- environment, do not edit this file's history. Author a new forward-fix
-- migration instead, and record the correction in that new file's
-- forward_fix_notes field.

-- Up Migration

CREATE TABLE wallet.ledger_entry (
  ledger_entry_id UUID PRIMARY KEY,
  member_id TEXT NOT NULL,
  amount INTEGER NOT NULL CHECK (amount >= 0),
  source_type TEXT NOT NULL,
  source_id TEXT NOT NULL,
  correlation_id TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ledger_entry_source_unique UNIQUE (source_type, source_id)
);

CREATE INDEX ledger_entry_member_id_idx ON wallet.ledger_entry (member_id);

GRANT SELECT, INSERT ON wallet.ledger_entry TO app_rw_user;

-- Down Migration

-- DROP TABLE ... RESTRICT alone only refuses when another object depends on
-- this table — it does not check row content. This explicit guard is what
-- actually enforces the rollback_notes' "only while empty" rule.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM wallet.ledger_entry LIMIT 1) THEN
    RAISE EXCEPTION 'wallet.ledger_entry is not empty; destructive rollback is prohibited once any row exists. Forward-fix only.';
  END IF;
END $$;

DROP TABLE wallet.ledger_entry RESTRICT;
